# Generated by Django 6.0 on 2025-12-18 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stuscore',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('kor', models.IntegerField(default=0)),
                ('eng', models.IntegerField(default=0)),
                ('math', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('avg', models.FloatField(default=0)),
                ('sdate', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
        ),
    ]
