# Generated by Django 6.0 on 2025-12-10 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='greade',
            new_name='grade',
        ),
    ]
