# Generated by Django 6.0 on 2025-12-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
