# Generated by Django 6.0 on 2025-12-10 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='rank',
        ),
    ]
