# Generated by Django 6.0 on 2025-12-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_student_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hobby',
            field=models.CharField(default='게임', max_length=100),
        ),
    ]
