# Generated by Django 6.0 on 2025-12-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='bhit',
            field=models.IntegerField(default=0),
        ),
    ]
