# Generated by Django 6.0 on 2025-12-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_board_bhit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='bfile',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='board',
            name='bgroup',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='board',
            name='bindent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='board',
            name='bstep',
            field=models.IntegerField(default=0),
        ),
    ]
