# Generated by Django 6.0 on 2025-12-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('bno', models.AutoField(primary_key=True, serialize=False)),
                ('btitle', models.CharField(max_length=1000)),
                ('bcontent', models.TextField(default='', null=True)),
                ('bfile', models.FileField(default='', null=True, upload_to='')),
            ],
        ),
    ]
