# Generated by Django 6.0 on 2025-12-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
