# Generated by Django 6.0 on 2025-12-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartData',
            fields=[
                ('cno', models.AutoField(primary_key=True, serialize=False)),
                ('cyear', models.CharField(max_length=4)),
                ('cdata', models.IntegerField(default=0)),
            ],
        ),
    ]
