# Generated by Django 6.0 on 2025-12-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('kor', models.IntegerField()),
                ('eng', models.IntegerField()),
                ('math', models.IntegerField()),
                ('total', models.IntegerField()),
                ('avg', models.FloatField()),
                ('rank', models.IntegerField()),
                ('grade', models.CharField(max_length=10)),
            ],
        ),
    ]
