# Generated by Django 6.0 on 2025-12-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=1)),
                ('grade', models.IntegerField(default=1)),
                ('gender', models.CharField(max_length=10)),
                ('hobby', models.CharField(default='게임', max_length=100)),
            ],
        ),
    ]
