# Generated by Django 6.0 on 2025-12-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
